Ntd1hc/feat/robfw 328/update readme and document
test-fullautomation/testresultwebapp pull request #6
Opened 2022-09-16 07:25 UTC by ngoan1608

Hi Thomas,

I have just updated the README files. Please review them first.

I am working with package's document and will add to this branch soon.

Thank you,
Ngoan

2022-09-27 11:13 UTC, test-fullautomation requested changes
Hi Ngoan,
thank you for your pulll-request.
Please look into my findings.
Thank you,
 Thomas

2022-09-27 11:13 UTC, test-fullautomation commented on README.md
Hi Ngoan,
the licence info must be removed here.
Thank you,
 Thomas

2022-09-27 11:13 UTC, test-fullautomation commented on README.md
> +    -   [How to install](#how-to-install)
Hi Ngoan,
'"how to install" is wrong here.
Thank you,
 Thomas

2022-09-27 11:13 UTC, test-fullautomation commented on README.md
> +### How to install
Hi Ngoan,
How to install is wrong here.
Somehow we should have at the end a small overview how to get the whole system run.
There was an architecture diagram as I remember. Some steps how to setup I have written in a readme. Can you please look if we can use this information. 
Best would be if this is part of  [TRWebApp's Documentation](https://github.com/test-fullautomation/testresultwebapp/blob/develop/TestResultWebApp/TestResultWebApp.pdf)
Thank you,
 Thomas

2022-09-27 11:13 UTC, test-fullautomation commented on README.md
> +-   [Usage](#usage)
Hi Ngoan,
a chapter how to upload data is missing.
RobotLog2DB...
Thank you,
 Thomas

2022-09-27 11:13 UTC, test-fullautomation commented on README.md
> +![IMG_BOSCH](packagedoc/additional_docs/pictures/Boschlogo.png) [Robert
Hi Ngoan,
I know, my first version was already not good :-)
The Bosch-Logo need to be aligned to the text. Please try to align it.
Thank you,
 Thomas

2022-09-27 11:13 UTC, test-fullautomation commented on README.md
> +displaying of test result data in a sophisticated way.
... which allows processing ***and*** displaying ...

2022-09-27 11:13 UTC, test-fullautomation commented on README.rst
> +`TRWebApp’s Documentation`_.
Hi Ngoan,
did you work on an update for this document, too?
I'm not sure, but I remember that you told this in our weekly sync.
Thank you,
 Thomas

2022-09-27 13:31 UTC, ngoan1608 commented
> Hi Ngoan, thank you for your pulll-request. Please look into my findings. Thank you, Thomas

Hi Thomas,

I have just updated some parts of package document and would like you to give your feeling about them.
There are the introduction section and document for datable view are under documenting.

Please review  the initial https://github.com/test-fullautomation/testresultwebapp/blob/ntd1hc/feat/ROBFW-328/update-readme-and-document/TestResultWebApp/TestResultWebApp.pdf file and let me know if it need to be improved.
I am trying to consolidate all the features and how to use them.

P/s: the missing sections and your findings will be fixed in next commits.

Thank you,
Ngoan

2022-09-28 15:26 UTC, test-fullautomation commented
Hi Ngoan,

very good! I looked into [TestResultWebApp.pdf](https://github.com/test-fullautomation/testresultwebapp/blob/ntd1hc/feat/ROBFW-328/update-readme-and-document/TestResultWebApp/TestResultWebApp.pdf).
It has small typos, but is already a very good starting point for somebody who want to use is.

At the beginning we should have a friendly hint, that somebody who want to use our WebApp need to have some knowledge about Web- and Database Technologies. 

Thank you,
 Thomas

2022-10-21 12:43 UTC, test-fullautomation commented
Hi Ngoan,
your input was very good!
I made some corrections and extensions and merge now.
Thank you,
 Thomas

2022-10-21 12:44 UTC, test-fullautomation approved these changes

2022-10-21 12:44 UTC, merged